import os
import json
import subprocess
import datetime
import sys

# Configuration
PROJECT_ROOT = r'F:\Aisaak\Projects\vibecode-town'
VENV_PYTHON = r'F:\BW\writer\ъ⑸援\crawl4ai\.venv\Scripts\python.exe'

def log(msg):
    print(f"[{datetime.datetime.now().strftime('%H:%M:%S')}] {msg}")

def scout():
    log("Stage -1: Scouting for high-signal technical assets...")
    # These are the topics selected for tomorrow
    scout_list = {
        "morning": {
            "type": "Magnet", 
            "topic": "The MCP USB-C Moment: Connecting Your First Server", 
            "urls": ["https://modelcontextprotocol.io/introduction"]
        },
        "lunch": {
            "type": "Beacon", 
            "topic": "Deconstructing Software 3.0: Karpathy's New Model", 
            "urls": ["https://karpathy.ai/blog/software-3.0"]
        },
        "evening": {
            "type": "FieldLog", 
            "topic": "Day 247: Scaling the RAG Wall with MUSU", 
            "urls": []
        }
    }
    scout_path = os.path.join(PROJECT_ROOT, 'research', 'scout-list.json')
    os.makedirs(os.path.dirname(scout_path), exist_ok=True)
    with open(scout_path, 'w') as f:
        json.dump(scout_list, f, indent=2)
    log(f"Scout list updated in {scout_path}")

def research():
    log("Stage 0: Crawl4AI Deep Capture...")
    scout_path = os.path.join(PROJECT_ROOT, 'research', 'scout-list.json')
    if not os.path.exists(scout_path):
        log("No scout list found. Run 'scout' first.")
        return

    with open(scout_path, 'r') as f:
        scout_list = json.load(f)
    
    for slot, data in scout_list.items():
        if data['urls']:
            log(f"Crawling {slot} content: {data['topic']}...")
            raw_dir = os.path.join(PROJECT_ROOT, 'research', 'raw', slot)
            os.makedirs(raw_dir, exist_ok=True)
            # In real automation, we run the crawler here.
            raw_file = os.path.join(raw_dir, "source.md")
            with open(raw_file, 'w', encoding='utf-8') as f:
                f.write(f"# RAW CAPTURE: {data['topic']}\n\n[Content placeholder for {data['urls'][0]}]")
    log("Research phase complete.")

def draft():
    log("Stage 1 & 2: Vibe-Musu Drafting Skeltons...")
    scout_path = os.path.join(PROJECT_ROOT, 'research', 'scout-list.json')
    with open(scout_path, 'r') as f:
        scout_list = json.load(f)

    for slot, data in scout_list.items():
        draft_path = os.path.join(PROJECT_ROOT, 'drafts', f"{slot}_v1.md")
        os.makedirs(os.path.dirname(draft_path), exist_ok=True)
        
        content = f"""---
title: "{data['topic']}"
pubDatetime: {datetime.datetime.now().isoformat()}
description: "Draft generated by Vibe Engine for {data['topic']}"
draft: true
tags: ["{data['type'].lower()}"]
---

# {data['topic']}

> [SYSTEM INSTRUCTION]: Use the {data['type']} prompt from factory/prompts.md to fill this draft.
> Refer to research/raw/{slot}/source.md for technical details.

[Awaiting LLM Synthesis...]
"""
        with open(draft_path, 'w', encoding='utf-8') as f:
            f.write(content)
        log(f"Created draft skeleton for {slot}")

def main():
    if len(sys.argv) < 2:
        print("Usage: python vibe_engine.py [scout|research|draft|all]")
        return
    
    mode = sys.argv[1]
    if mode == 'scout' or mode == 'all': scout()
    if mode == 'research' or mode == 'all': research()
    if mode == 'draft' or mode == 'all': draft()
    
    log("Cycle phase complete. Ready for LLM synthesis.")

if __name__ == '__main__':
    main()
